version: 0.2
phases:
  install:
    commands:
      - echo Installing Maven...
      - apt-get update && apt-get install -y maven  # Install Maven if missing
  pre_build:
    commands:
      - echo Compiling the Spring Boot app...
      - mvn clean package  # Build the JAR file
  build:
    commands:
      - echo Building Docker image...
      - docker build -t 339039570958.dkr.ecr.us-east-1.amazonaws.com/inventory-app:latest .
  post_build:
    commands:
      - echo Pushing Docker image...
      - docker push 339039570958.dkr.ecr.us-east-1.amazonaws.com/inventory-app:latest
